// Static daily news brief — auto-generated by scripts/refresh-news-brief.mjs
// scheduled via .github/workflows/refresh-brief.yml.
//
// To refresh manually:   node scripts/refresh-news-brief.mjs
// To hide the panel:     export NEWS_BRIEFS = [] and commit.

export const NEWS_BRIEFS = [
  {
    "label": "Pre-Market",
    "text": "Pre-market view of trending names: ReTo Eco-Solutions (RETO) leads the trending board with a +676.3% move, joined by VEEA +149.3% and MEDS +87.2%. On the downside, WING -12.1% and CRCL -11.4%. On the news front, RETO headlines highlight: \"ReTo Eco-Solutions stock skyrockets on heavy speculative trading with no clear fresh catalyst\"."
  }
];

export const BRIEF_GENERATED_AT = "2026-09-16";
