// Static daily news brief — auto-generated by scripts/refresh-news-brief.mjs
// scheduled via .github/workflows/refresh-brief.yml.
//
// To refresh manually:   node scripts/refresh-news-brief.mjs
// To hide the panel:     export NEWS_BRIEFS = [] and commit.

export const NEWS_BRIEFS = [
  {
    "label": "Pre-Market",
    "text": "Pre-market view of trending names: Palantir Technologies Inc. (PLTR) leads the trending board with a +10.3% move, joined by MNDY +6.3% and ABCL +6.1%. On the downside, BTC-USD -0.0%. On the news front, SMCI headlines highlight: \"Super Micro Computer, Inc. (NASDAQ:SMCI) shares climb; margin recovery alters financing dynamics\"."
  }
];

export const BRIEF_GENERATED_AT = "2026-08-10";
