// Static daily news brief — auto-generated by scripts/refresh-news-brief.mjs
// scheduled via .github/workflows/refresh-brief.yml.
//
// To refresh manually:   node scripts/refresh-news-brief.mjs
// To hide the panel:     export NEWS_BRIEFS = [] and commit.

export const NEWS_BRIEFS = [
  {
    "label": "Pre-Market",
    "text": "Pre-market view of trending names: Trident Digital Tech Holdings L (TDTH) leads the trending board with a +49.0% move, joined by BJDX +37.5% and CCHH +19.0%. On the downside, RIVN -12.9% and 005930.KS -6.9%. On the news front, RIVN headlines highlight: \"Rivian stock falls 10% as company sells 75 million shares to raise capital\"."
  }
];

export const BRIEF_GENERATED_AT = "2026-07-07";
